cols = [
    {"name": "time"},  # {"name": "Время"},
    {"name": "driving_experience_5"},  # {"name": "Стаж(лет)_5"},
    {"name": "week_day"},  # {"name": "День недели"},
    {"name": "month"},  # { "name": "Месяц"},
    {"name": "type_of_road"},  # {"name": "Вид ДД (одностороннее 1, двухстороннее 2, смешанная 1.2)"},
    {"name": "traffic_direction_separator"},  # {"name": "Разделитель направлений движения (только разметка 0, разделительная полоса 1, барьерные ограждения 2)"},
    {"name": "intersection_type"},  # {"name": "Тип перекрестка (т - 1, у - 2, х - 3, ж - 4)"},
    {"name": "traffic_light"},  # {"name": "Светофорное регулирование(0- нет, 1- есть)"},
    {"name": "availability_of_a_pedestrian_crossing_within_a_radius_of_50_m"},    # {"name": "Наличие пешеходного перехода в радиусе 50 м (1 есть, 0 нет)"},
    {"name": "visibility,_code_(VV)"},  # {"name": "Видимость, шифр (VV); -1 если нет ограничений"},
    {"name": "part_of_the_day"},  # {"name": "Часть суток"},
    {"name": "int_250"},  # {"name": "Инт_250"},
    {"name": "road_width_5"},  # {"name": "Ширина дороги"},
    {"name": "number_of_forward_lanes_(total_number_in_all_directions)"},  # {"name": "Кол. пол. в прям. напр. (общ. Кол. во всех напр.)"},
    {"name": "number_of_left_lanes_(in_all_directions:_oncoming_and_parallel)"},   # {"name": "Кол. ЛЕВ полос (во всех напр.: встечн. и попутн.)"},
    {"name": "number_of right_lanes_(in_all_directions)"},   # {"name": "Кол.ПРАВ полос (во всех напр.: встечн. и попутн.)"},
    {"name": "left_stripe_length"},  # {"name": "Длина Левого кармана ПРС (мин. всех. напр)"},
    {"name": "longitudinal_slope"},  # {"name": "Продольный уклон (за 100 м до контр. Участ) ‰"},
    {"name": "right_stripe_length"},  # {"name": "Длина Правого кармана ПРС  (мин. всех. напр)"},
    {"name": "distance_to_parking"},	 # 	    # {"name": "Расстояние до Парковки (от ближ. края дома по рассматриваемой улице)"},
    {"name": "distance_to_bus_stop_from_the_center_of_the_house"},	 # 	    # {"name": "Расстояние до авт. Ост. от цента дома"},
    {"name": "max_speed"},  # {"name": "max_speed"},
    {"name": "air_temperature"},  # {"name": "Температура воздуха (t воздуха), С°"},
    {"name": "soil_temperature"},  # {"name": "Температура почвы (t почвы), С°"},
    {"name": "dew_point_temperature"},  # {"name": "Температура точки росы (DP), С°"},
    {"name": "partial_pressure_of_water_vapor"},  # {"name": "Парциальное давление водяного пара (ps), Па"},
    {"name": "relative_humidity"},  # {"name": "Относительная влажность воздуха (?), %;"},
    {"name": "saturation_deficit"},  # {"name": "Дефицит насыщения (d), г/м?"},
    {"name": "atmospheric_pressure_at_station_level"},	 # 	    {"name": "Атмосферное давление на уровне станции(P станции), г.Па"},
    {"name": "atmospheric_pressure_at_sea_level"},  # {"name": "Атмосферное давление на уровне моря (P моря), г.Па"},
    {"name": "wind_speed"},  # {"name": "Скорость ветра, м/с"},
    {"name": "precipitation_mm"},  # {"name": "Осадки, мм"},
    {"name": "vehicle_type_category "},  # {"name": "Тип ТС_вид (1- велосипеды; 2- мотоциклы; 3- легковые автомобили; 4 - автобусы; 5- спец техника; 6- грузовые автомобили)"},
    {"name": "general_injuries"},  # {"name": "ТРАВМАТИЗМ"},
    # {"name": "color"},	 # 	    # {"name": "Цвет"},
    # {"name": "driving_experience_years"},	 # 	    # {"name": "Стаж(лет)_категории"},
    # {"name": "location",  "need_encode": True},	 # 	    # {"name": "Место (ц-1, ж-2, и-3, к-4)",  "need_encode": True},
]
primary_column = 'general_injuries'
